#!/usr/bin/python3

import os
import argparse
from tortilla8.guacamole import guacamole

def pos_int(value):
    ivalue = int(value)
    if ivalue < 1:
         raise argparse.ArgumentTypeError("%s is an invalid positive int value." % value)
    return ivalue

parser = argparse.ArgumentParser(description=
'''
Execute a rom to quickly check for errors. The program counter, hex instruction (the two
bytes that make up the opcode), and mnemonic are printed to the screen immediately after
the execution of that operation code. All errors (info, warning, and fatal) are printed
to screen.
''')
parser.add_argument('rom', help='ROM to load and play.')
parser.add_argument("-f","--frequency",   type=pos_int, default=5,  help='Frequency (in Hz) to target for CPU.')
parser.add_argument("-st","--soundtimer", type=pos_int, default=60, help='Frequency (in Hz) to target for the audio timmer.')
parser.add_argument("-dt","--delaytimer", type=pos_int, default=60, help='Frequency (in Hz) to target for the delay timmer.')
parser.add_argument('-i','--initram', help='Initialize RAM to all zero values.', action='store_true')
parser.add_argument('-ls','--legacy_shift', help='Use the legacy shift method of bit shift Y and storing to X.', action='store_true')
parser.add_argument("-e","--enforce_instructions", default='None', help='Warning to log if an unoffical instruction is executed. Options: None Info Warning Fatal')
opts = parser.parse_args()

if not os.path.isfile(opts.rom):
    raise OSError("File '" + opts.rom + "' does not exist.")

guac = guacamole(opts.rom, opts.frequency, opts.soundtimer, opts.delaytimer, opts.initram, opts.legacy_shift, opts.enforce_instructions)
guac.log_to_screen = True
try:
    while True:
        guac.run()
except KeyboardInterrupt:
    pass

