#!/usr/bin/env python3

from os import path
from sys import platform
from argparse import ArgumentParser
from tortilla8.platter import platter

def pos_int(value):
    ivalue = int(value)
    if ivalue < 1:
         raise ArgumentTypeError( value + " is an invalid positive int value." )
    return ivalue

parser = ArgumentParser(description=
'''
Start a text (unicode) based Chip8 emulator which disaplys a game screen, all
registers, the stack, recently processed instructions, and a console to log
any issues that occur.
''')
parser.add_argument('rom', help='ROM to load and play.')
group = parser.add_mutually_exclusive_group()
group.add_argument('-f','--frequency', type=pos_int, default=10,help='''CPU frequency to target, minimum 1Hz. 10Hz by default. CPU frequency can be adjusted in platter.''')
group.add_argument('-s','--step', help='Start the emulator in "step" mode. Allows for execution of a single instruction at a time.', action='store_true')
parser.add_argument('-d','--drawfix', help='Enable anti-flicker, stops platter from drawing to the screen when sprites are only removed.', action='store_true')
parser.add_argument('-i','--initram', help='Initialize RAM to all zero values. Needed to run some ROMs that assume untouched addresses to be zero. By default RAM address without values are not initalized, accessing them will cause an Emulation Error.', action='store_true')
parser.add_argument('-a','--audio', help='Path to audio to play for Sound Timer, or "off" to prevent sound from playing. By default a 440Hz square wave is used.')
parser.add_argument("-st","--soundtimer", type=pos_int, default=60, help='Frequency to target for the audio timmer. 60Hz by default.')
parser.add_argument("-dt","--delaytimer", type=pos_int, default=60, help='Frequency to target for the delay timmer. 60Hz by default.')
parser.add_argument('-ls','--legacy_shift', help='Use the legacy shift method of bit shift Y and storing to X. By default the newer method is used where Y is ignored and X is bitshifted then stored to itself.', action='store_true')
parser.add_argument("-e","--enforce_instructions", default='None', help='Warning to log if an unoffical instruction is executed. By default, no errors are logged. Options: None Info Warning Fatal')
parser.add_argument("-r","--rewind_depth", type=pos_int, default=1000, help='Number of instructions back to be recorded to enable rewinding. To disable set to zero or "off". By default 1000 instructions are recorded.')
parser.add_argument("-u","--unicode", nargs='*', help='Forces unicode on or off for the menu and game screen. Valid values are: On, Off, Menu-On, Menu-Off, Game-On, Game-Off. By default, unicode support is determined by the OS. Mac displays a unicode game screen, Windows displays no unicode, and GNU/Linux displays both the game and menu in unicode.')

opts = parser.parse_args()

if not path.isfile(opts.rom):
    raise OSError("File '" + opts.rom + "' does not exist")

if opts.step:
    opts.frequency = 1000000 # 1 Ghz

screen_unicode = False if platform == 'win32' else True
menu_unicode   = True  if platform == 'linux' else False
if opts.unicode:
    if len(opts.unicode) > 2:
        raise IOError("Too many values following the '--unicode' flag.")
    for val in opts.unicode:
        val = val.lower().split('-')
        if   val[0] == 'menu' and val[1]== 'on':
            menu_unicode = True
        elif val[0] == 'menu' and val[1]== 'off':
            menu_unicode = False
        elif val[0] == 'game' and val[1]== 'on':
            game_unicode = True
        elif val[0] == 'game' and val[1]== 'off':
            game_unicode = False:
        else:
            raise IOError("Unknown value following the '--unicode' flag.")

disp = platter( opts.rom, opts.frequency, opts.soundtimer, opts.delaytimer,
                opts.initram, opts.legacy_shift, opts.enforce_instructions,
                opts.rewind_depth, opts.drawfix, screen_unicode, menu_unicode,
                opts.audio )
disp.start(opts.step)

